repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^uvex_transients/config\.yaml$
      - id: check-yaml
        name: check-yaml (custom tags)
        args: [--unsafe]
        files: ^uvex_transients/config\.yaml$
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=2000]
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.6
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/crate-ci/typos
    rev: v1.50.1
    hooks:
      - id: typos
